---
name: Build and Deploy
on:
  push:
    branches:
      - master
env:
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }} # Address of Octopus Deploy instance (i.e. https://demo.octopus.app)
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }} # API key used with Octopus Deploy instance
  OCTOPUS_SPACE: 'Default' # Or you can specify a Space ID

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-dotnet-artifacts
          path: ./publish

      - name: Create ZIP package
        run: |
          cd ./publish
          zip -r my-dotnet-artifacts1.0.1.zip .
          mv my-dotnet-artifacts1.0.1.zip ../my-dotnet-artifacts1.0.1.zip

      - name: Install Octopus CLI 🐙
        uses: OctopusDeploy/install-octopus-cli-action@v3
        with:
          version: '*'

      - name: Push build information to Octopus Deploy 🐙
        uses: OctopusDeploy/push-build-information-action@v3
        with:
          packages: |
            'my-dotnet-artifacts'
          version: '1.0.1'

