name: .NET Framework CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: Windows-Latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Setup .NET Framework
    #  uses: actions/setup-dotnet@v1
     # with:
     #   dotnet-version: '4.7.2'

    - name: Restore NuGet packages
      run: nuget restore CarpeLibrum_BookClub_23.sln

 #   - name: Build
 #     run: "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" /p:Configuration=Release CarpeLibrum_BookClub_23\CarpeLibrum_BookClub_23.csproj
      
 #   - name: Setup MSBuild
  #    uses: microsoft/setup-msbuild@v1.0.0

 #   - name: Build
  #    run: MSBuild /p:Configuration=Release /p:Platform="Any CPU" .\CarpeLibrum_BookClub_23\CarpeLibrum_BookClub_23.csproj

#    - name: Publish
#      run: MSBuild /t:Publish /p:Configuration=Release /p:Platform="Any CPU" YourProject.csproj /p:PublishDir=bin\Publish\