name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Or whichever version you're using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Create ZIP package
      run: |
        cd ./publish
        zip -r my-dotnet-artifacts.zip .
        mv my-dotnet-artifacts.zip ../my-dotnet-artifacts.zip

    - name: Setup Octopus CLI
      uses: octopusdeploy/cli-setup-action@v1
      with:
        version: '7.4.0'
      env:
        OCTOPUS_CLI_SERVER: ${{ secrets.OCTOPUS_SERVER_URL }}
        OCTOPUS_CLI_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}

    - name: Push package to Octopus Deploy
      run: |
        octo push --package ../my-dotnet-artifacts.zip --replace-existing --server $OCTOPUS_CLI_SERVER --apiKey $OCTOPUS_CLI_API_KEY

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-dotnet-artifacts
        path: ./publish